line-length = 100
extend-exclude = ["docs/source/conf.py"]

[format]
quote-style = "single"
docstring-code-format = true

[lint.per-file-ignores]
"__init__.py" = ["F401"]

[lint.pydocstyle]
convention = "google"
