{% set name = "rsatoolbox" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rsatoolbox-{{ version }}.tar.gz
  sha256: fee6e0134c345f4d7e7f2d7bdde20b13724e9d0d32f89e8b22b7fc17ed21ef9a

build:
  skip: true  # [py<37 or py>310 or py2k]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython # >=3.0.0a11
    - numpy >=1.21.2
    - scipy
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('scipy') }}
    - pandas
    - scikit-learn
    - scikit-image
    - matplotlib-base
    - h5py
    - joblib
    - tqdm
    - coverage


test:
  imports:
    - rsatoolbox
  commands:
    - pip check
    - python -m unittest -v rsatoolbox.test
  requires:
    - pip

about:
  home: https://github.com/rsagroup/rsatoolbox
  summary: Representational Similarity Analysis (RSA) in Python
  license: MIT
  license_file: LICENSE
  doc_url: https://rsatoolbox.readthedocs.io/
  dev_url: https://github.com/rsagroup/rsatoolbox

extra:
  recipe-maintainers:
    - ilogue
