name: Style and Typing checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  statuses: write

jobs:

  style:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install ruff
    - name: Ruff output to file
      run: ruff check -ne -o ruff.log --output-format concise
    - name: Ruff output as annotations
      run: echo "$(ruff check -e --output-format github)"
    - name: Process Ruff output
      run: python devops/style_assistant.py ${{ github.run_id }} ${{ github.job }} ${{ github.event.pull_request.head.sha }}
    - name: Report status
      run: gh api ${{ env.DEVOPS_ASST_API_ARGS }}


  typing:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Python Version
      run: python --version
    - name: Update Pip
      run: python -m pip install --upgrade pip
    - name: Install dependencies
      run: pip install build setuptools pandas-stubs types-tqdm pyright
    - uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
    - name: Build package
      run: python -m build --sdist
    - name: Install rsatoolbox 
      run: pip install dist/*
    - name: Pyright (on main)
      continue-on-error: true
      run: pyright > pyright_main.log
    - name: Uninstall rsatoolbox 
      run: pip uninstall -y rsatoolbox
    - name: Remove builds
      run: rm dist/*
    - uses: actions/checkout@v4
      with:
        clean: false
        fetch-depth: 0
    - name: Build package
      run: python -m build --sdist
    - name: Install rsatoolbox 
      run: pip install dist/*
    - name: Pyright (on PR)
      continue-on-error: true
      run: pyright > pyright_pr.log
    - name: Process Pyright output
      run: python devops/typing_assistant.py ${{ github.run_id }} ${{ github.job }} ${{ github.event.pull_request.head.sha }}
    - name: Report status
      run: gh api ${{ env.DEVOPS_ASST_API_ARGS }}
